### ISSUE TITLE
Yii2 Support

### ISSUE THREAD

**Issue by saada** [ddinchev/yii-factory-girl#3]
Hey!

I admire your effort to put this all together. I would like to contribute to this library to add support for Yii2.
Any suggestion on where to start? Do you want to have backwards compatibility with Yii1? Should I create a new project called `yii2-factory-girl` or something?

**Comment by ddinchev** [comment]
Hey @saada, I've already started doing some progress on porting to Yii2 as I'm porting the project I created `yii-factory-girl` to Yii2. We can collaborate on this if you want?

**Comment by saada** [comment]
I was gonna do the effort alone anyway. So doing it together might speed things up! 
Could you list your findings and some guidelines? Or some task list like below?
- [x] task 1
- [ ] task 2
- [ ] task 3

**Comment by ddinchev** [comment]
Closing the issue as we have decided to do a wrapper of https://github.com/thephpleague/factory-muffin in https://github.com/saada/yii2-factory-muffin

**Comment by saada** [comment]
just finished the plugin. It's and ready to be used. Enjoy!
